### ISSUE TITLE
Incorrect route names

### ISSUE THREAD

**Issue by gleb-chipiga** [aio-libs/sockjs#13]
Trying to run a chat example with aiohttp == 18.3

```python
> python chat.py 
Traceback (most recent call last):
  File "chat.py", line 33, in <module>
    sockjs.add_endpoint(app, chatSession, prefix='/sockjs/')
  File "/home/gleb/.python-virtualenvs/sockjs/lib/python3.5/site-packages/sockjs/route.py", line 59, in add_endpoint
    hdrs.METH_GET, prefix, route.greeting, name=route_name)
  File "/home/gleb/.python-virtualenvs/sockjs/lib/python3.5/site-packages/aiohttp/web_urldispatcher.py", line 481, in add_route
    self.register_route(route)
  File "/home/gleb/.python-virtualenvs/sockjs/lib/python3.5/site-packages/aiohttp/web_urldispatcher.py", line 452, in register_route
    raise ValueError('Incorrect route name value, '
ValueError: Incorrect route name value, Route name should be a sequence of python identifiers separated by dot or column
```

**Comment by asvetlov** [comment]
Fixed by aiohttp==0.18.4
Thanks for report
